#GSO Forrit - Afangaverkefni
txtfile = open("testfile.txt","w")
txtfile.write ("Echo world, ")
txtfile.close()
txtfile = open("testfile.txt","a")
txtfile.write(" \nThis is my second line.")
txtfile.write(" \nThis is the third  line.")
txtfile.close()
txtfile = open("testfile.txt", "r")
print (txtfile.read())
